### ISSUE TITLE
Dimensions without stage

### ISSUE THREAD

**Issue by luca-rath** [sulu/SuluContentBundle#151]
There is a use case for some data to be independent of the workflow. e.g. you could have some data, which is constantly fetched from an external api and you have some content data which is managed in the sulu admin.

For the content data, you may want to enable the workflow, but the api data should always be the same, no matter if an entity is `unpublished`, `draft` or `published`.

This would require to make `Dimension::$stage` nullable, But I'm not sure, if there are side-effects. I guess the sorting logic, which is responsible to return the least specific `DimensionContent` first and the most specific `DimensionContent` last has to be adjusted.

**Comment by alexander-schranz** [comment]
I did discuss this with @chirimoya where we did implement a Product Entity which has data from a external service. And we decided not to support unstaged things, because it make it more complex and has also impact on the performance by always create the unstaged dimensions.

Instead this entity should have itself a translated entity so for Example in case of Product it will look like this:

 - `Product` (ContentRichEntityInterface) 
 - `ProductTranslation` contains translated fields which are not part of publishing process
 - `ProductDimensionContent` content is always in a specific stage

This also make it a huge different between what is part of your `Domain` logic e.g. `title`, `code` are in your domain `ProductTranslation` and you have there the specific getter and setter. And Content is only for publish able content which will be reviewed.
