### ISSUE TITLE
Adjust interface of services to accept locale instead of dimensionAttributes array

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluContentBundle#84]
This issue relates to #87.

Right now, most of the public services of the bundle (`ContentPersister`, `ContentWorkflow`, `ContentResolver`) accept a `dimensionAttributes` array. This is needed for flexibility in case somebody adds an additional attribute to the `Dimension` entity. But it also causes some inconsistencies and makes the interface of this services harder to understand/error prone. 

For example, we should always change the `DimensionContent` of the `draft` stage when modifying/persisting new content. Unfortunately, right now it is possible to call the `ContentPersister` with a `dimensionAttributes` array that contains `['stage' => 'live']`. This is probably not desired as it would modify the content of the website but the admin would still display the old content. 

If we decide to allow only a `stage` and a `locale` attribute, we could remove the `dimensionAttributes` parameter from the public interface of our services. This would make the services more concise and easier to use.

**Comment by niklasnatter** [comment]
After using the bundle in different projects, I changed my mind on this. During development I quickly got used to the `dimensionAttributes` parameter and did not think about it a lot after that. I still think removing the `dimensionAttributes` parameter would make our interfaces simpler, but it would also remove a lot of flexibility. For example, it would not be possible to implement something like the `getDefaultAttributes` method that was added in https://github.com/sulu/SuluContentBundle/pull/174/files#diff-1edf6cffae3d6fc5c10993e29318d205d1a7fb67f3ae6ada8d97a7a61efcf828R40 

Therefore, instead of removing the `dimensionAttributes` parameter, we should make sure to use and handle it consistently in our services. If we do that, I am quite sure our users will quickly get used to the concept 🙂
