### ISSUE TITLE
Set the current workflowPlace of the ContentWorkflow only on a specific DimensionContent

### ISSUE THREAD

**Issue by nnatter** [sulu/SuluContentBundle#92]
The `ContentWorkflow` service allows to apply a transition on a `contentRichEntity` and given `dimensionAttributes`. Because the `currentPlace` of an `contentRichEntity` might differ based on the locale, the `currentPlace` is stored on the `DimensionContent` entity. This makes sense, as the english version of a page might be published while the german version is still in review.

In most setups, there are 4 `DimensionContent` entities that are related to a specific locale:
* Draft Stage / Unlocalized
* Draft Stage / Localized
* Live Stage / Unlocalized
* Live Stage / Localized

Right now, all of these `DimensionContent` entities contain a `currentPlace` property, but the ContentWorkflow only updates the `currentPlace` property of the `Draft Stage / Localized` `DimensionContent`. This means the database will contain the following values for the `currentPlace` attributes, if a `contentRichEntity` is published in a specific locale:
* Draft Stage / Unlocalized: `unpublished`
* Draft Stage / Localized: `published`
* Live Stage / Unlocalized: `unpublished`
* Live Stage / Localized: `unpublished`

In my opinion, it is very confusing that the `Draft Stage / Localized` `DimensionContent` is the only entity that contains the correct `currentPlace`. We should adjust this behaviour to one of the following strategies:

* Update the `currentPlace` of all entities. This is problematic because there is no "right" value for the unlocalized `DimensionContent`
* Set the `currentPlace` only on the `Draft Stage / Localized` `DimensionContent`. Set the `currentPlace` of all other `DimensionContent` entities to `null`

**Comment by wachterjohannes** [comment]
in my opinion it should look like this:

* Draft Stage / Unlocalized: null
* Draft Stage / Localized: published
* Live Stage / Unlocalized: null
* Live Stage / Localized: published

**Comment by nnatter** [comment]
After thinking through this a second time, I have the opinion that we should save the `currentPlace` **only on the `Draft Stage / Localized``DimensionContent`** and set the `currentPlace` of all other `DimensionContent` entities to `null`.

**Comment by luca-rath** [comment]
It's necessary to have `workflowPublished` on the `Live Stage / Localized` `DimensionContent` to allow sorting by published date.

I'm using following code to evaluate `publishedState` of a `DimensionContent`.
That code should work with both, `DRAFT` and `LIVE` dimensions.

* `getPublishedState() === true` means `published`
* `getPublishedState() === false && getPublished() !== null` means `unpublished`, but a `published` version exists.
* `getPublishedState() === false && getPublished() === null` means `unpublished`, without a `published` version.

The `SmartContentItem` js container uses that logic to display the published indicator for each item.

~~~php
public function getPublished(): ?\DateTimeInterface
{
    $contentProjection = $this->getContentProjection();
    $dimension = $contentProjection->getDimension();

    if (null === $dimension->getLocale()) {
        return null;
    }

    if (!$contentProjection instanceof WorkflowInterface) {
        return null;
    }

    return $contentProjection->getWorkflowPublished();
}

public function getPublishedState(): bool
{
    $contentProjection = $this->getContentProjection();
    $dimension = $contentProjection->getDimension();

    if (null === $dimension->getLocale()) {
        return false;
    }

    if (DimensionInterface::STAGE_LIVE === $dimension->getStage()) {
        return true;
    }

    if (!$contentProjection instanceof WorkflowInterface) {
        return true;
    }

    return $contentProjection->getWorkflowPlace() === WorkflowInterface::WORKFLOW_PLACE_PUBLISHED;
}
~~~

Therefore it's necessary to have `workflowPlace` and `workflowPublished` set on both, `Draft Stage / Localized` and `Live Stage / Localized`.

The `workflowPlace` and `workflowPublished` on `Live Stage / Localized` should NOT always be a copy of `Draft Stage / Localized`, because the following should be a valid state:

* `Draft Stage / Localized`: `workflowPlace: draft, workflowPublished: 2020-04-19`
* `Live Stage / Localized`: `workflowPlace: published, workflowPublished: 2020-04-19`

One way to achieve this would be a `PublishCompletedSubscriber`, that copies `workflowPlace` and `workflowPublished` from `Draft Stage / Localized` to `Live Stage / Localized`.

**Comment by nnatter** [comment]
I feel like your comment is related to different areas, so i am trying to split the answer into different parts:

1. You are stating that your code should work for `draft` and `live` dimensions? Why is this the case? Do you need the information on the website?

2. The only place your code uses the `workflowPlace` is when you already know that the `locale` of the dimension is not null and the `stage` is not `live`. Hence you are only accessing it on the `Draft / Localized` dimension right?

3. I think I agree with you that there should be a `workflowPublished` set on the `Live / Localized` dimension. But this should be discussed in a different issue in my opinion 🙂

4. Unfortunately, a `PublishCompletedSubscriber` is not possible easily. This is because the `Live / Localized` dimension is not flushed and therefore might not exist at this point (for example, when the page is first published). This is even more complex than #129 because we would need a second flush to flush the changes to the `Live / Localized` dimension 🙈
